### ISSUE TITLE
Getting "java.lang.OutOfMemoryError: GC overhead limit exceeded" error while training

### ISSUE THREAD

**Issue by gangulypritha** [ppasupat/WikiTableQuestions#2]
Hello,

I was experimenting with the WikiTable Questions dataset. I have a new set of tables where each table has more number of questions. 
I tried training but after processing around 5 lakhs examples, it shows "java.lang.OutOfMemoryError: GC overhead limit exceeded" error. How can I fix this error? 
It would be really helpful if you could help me with this.

Thanks,
Pritha.

**Comment by ppasupat** [comment]
Hi Pritha. Since this seems to be a SEMPRE error, would you mind reposting the issue on the SEMPRE project (https://github.com/percyliang/sempre)? Thank you.
